project/server/teacher/forms.py
# project/server/teacher/forms.py


from flask_wtf import Form
from wtforms import TextField, DateField, TextAreaField
from wtforms.validators import DataRequired, Length, ValidationError

from project.server.models import Course


class AddCourseForm(Form):
    name = TextField(
        'Course Name',
        validators=[DataRequired(), Length(min=3, max=40)])
    description = TextAreaField(
        'Course Description',
        validators=[DataRequired()]
    )
    subject = TextField(
        'Subject',
        validators=[DataRequired()]
    )
    start_date = DateField(
        'Start Date',
        validators=[DataRequired()]
    )
    end_date = DateField(
        'End Date',
        validators=[DataRequired()]
    )

    def validate_name(self, field):
        if Course.query.filter_by(name=field.data).first():
            raise ValidationError('Sorry. That course name is already taken.')


class UpdateCourseForm(Form):
    name = TextField(
        'Course Name',
        validators=[DataRequired(), Length(min=3, max=40)])
    description = TextAreaField(
        'Course Description',
        validators=[DataRequired()]
    )
    subject = TextField(
        'Subject',
        validators=[DataRequired()]
    )
    start_date = DateField(
        'Start Date',
        validators=[DataRequired()]
    )
    end_date = DateField(
        'End Date',
        validators=[DataRequired()]
    )

project/server/teacher/__init__.py
# project/server/student/__init__.py

project/server/teacher/views.py
# project/server/teacher/views.py


###########
# imports #
###########

from functools import wraps
from flask import render_template, Blueprint, request, flash, redirect, url_for
from flask.ext.login import login_required, current_user
from sqlalchemy import exc

from project.server import db
from project.server.models import Course
from project.server.teacher.forms import AddCourseForm, UpdateCourseForm


##########
# config #
##########

teacher_blueprint = Blueprint('teacher', __name__,)


###########
# helpers #
###########

def get_courses(user_id):
    return Course.query.filter_by(teacher_id=user_id).all()


def get_single_course(course_id):
    return Course.query.filter_by(id=course_id).first()


def validate_teacher(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if current_user.is_teacher() is False:
            flash(
                'You do not have the correct permissions to view that page.',
                'warning'
            )
            return redirect(url_for('user.login', next=request.url))
        return f(*args, **kwargs)
    return decorated_function


##########
# routes #
##########


@teacher_blueprint.route('/teacher/courses')
@login_required
@validate_teacher
def show_courses():
    return render_template(
        '/teacher/courses.html', courses=get_courses(current_user.get_id())
    )


@teacher_blueprint.route('/teacher/course/<int:course_id>')
@login_required
@validate_teacher
def show_single_course(course_id):
    return render_template(
        '/teacher/description.html',
        single_course=get_single_course(course_id)
    )


@teacher_blueprint.route(
    '/teacher/add_course',
    methods=['GET', 'POST']
)
@login_required
@validate_teacher
def add_course():
    form = AddCourseForm(request.form)
    if form.validate_on_submit():
        new_course = Course(
            name=form.name.data,
            description=form.description.data,
            subject=form.subject.data,
            start_date=form.start_date.data,
            end_date=form.end_date.data,
            teacher_id=current_user.get_id()
        )
        try:
            db.session.add(new_course)
            db.session.commit()
            flash('Thank you for adding a new course.', 'success')
            return redirect('/teacher/courses')
        except exc.SQLAlchemyError:
            flash('Something went wrong.', 'danger')
            return redirect('/teacher/courses')
    return render_template('/teacher/add.html', form=form)


@teacher_blueprint.route(
    '/teacher/update_course/<int:course_id>',
    methods=['GET', 'POST']
)
@login_required
@validate_teacher
def update_course(course_id):
    form = UpdateCourseForm(request.form)
    if form.validate_on_submit():
        update_course = get_single_course(course_id)
        update_course.name = form.name.data
        update_course.description = form.description.data
        update_course.subject = form.subject.data
        update_course.start_date = form.start_date.data
        update_course.end_date = form.end_date.data
        try:
            db.session.commit()
            flash('Course updated. Thank you', 'success')
            return redirect('/teacher/course/{0}'.format(course_id))
        except exc.SQLAlchemyError:
            flash('Something went wrong.', 'danger')
            return redirect('/teacher/course/{0}'.format(course_id))
    return render_template(
        '/teacher/update.html',
        form=form,
        single_course=get_single_course(course_id)
    )

project/client/templates/teacher/add.html
{% extends "_base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<div class="body-content">
  <div class="row">
    <div class="col-md-12">
      <h1>Add Course</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">

    <form class="form" role="form" method="post" action="">

      {{ form.csrf_token }}
      {{ form.hidden_tag() }}
      {{ wtf.form_errors(form, hiddens="only") }}

      <div>

        {{ wtf.form_field(form.name) }}
        {{ wtf.form_field(form.description) }}
        {{ wtf.form_field(form.subject) }}
        {{ wtf.form_field(form.start_date, type="date") }}
        {{ wtf.form_field(form.end_date, type="date") }}

        <button class="btn btn-success" type="submit">Add Course!</button>

      </div>

    </form>

    </div>
  </div>
</div>

{% endblock %}

project/client/templates/teacher/courses.html
{% extends "_base.html" %}

{% block content %}

<div class="body-content">
  <div class="row">
    <div class="col-md-12">
      <h1>All Courses</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
        {% if courses %}
          <ul>
            {% for course in courses %}
              <li><a href="{{ url_for('teacher.show_single_course', course_id=course.id) }}">{{ course.name }}</a></li>
            {% endfor %}
          </ul>
        {% else %}
          <p>You are not teaching any courses.</p>
        {% endif %}
    </div>
  </div>
</div>

{% endblock %}

project/client/templates/teacher/description.html
{% extends "_base.html" %}

{% block content %}

<div class="body-content">
  <div class="row">
    <div class="col-md-12">
      <h1>{{ single_course.name }}</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <p>{{ single_course.description }}</p>
      <p>{{ single_course.start_date.strftime('%Y-%m-%d') }}</p>
      <p>{{ single_course.end_date.strftime('%Y-%m-%d') }}</p>
      <p><a class="btn btn-default btn-sm" href="{{ url_for('teacher.update_course', course_id=single_course.id) }}" role="button">Edit</a></p>
    </div>
  </div>
</div>

{% endblock %}

project/client/templates/teacher/update.html
{% extends "_base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<div class="body-content">
  <div class="row">
    <div class="col-md-12">
      <h1>Update Course</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">

    <form class="form" role="form" method="post" action="">

      {{ form.csrf_token }}
      {{ form.hidden_tag() }}
      {{ wtf.form_errors(form, hiddens="only") }}

      <div>

        {{ wtf.form_field(form.name, value=single_course.name) }}
        <label class="control-label" for="description">Course Description</label>
        <textarea class="form-control" id="description" name="description" required>{{ single_course.description }}</textarea>
        {{ wtf.form_field(form.subject, value=single_course.subject) }}
        {{ wtf.form_field(form.start_date, type="date", value=single_course.start_date.strftime('%Y-%m-%d')) }}
        {{ wtf.form_field(form.end_date, type="date", value=single_course.end_date.strftime('%Y-%m-%d')) }}

        <button class="btn btn-success" type="submit">Update Course!</button>

      </div>

    </form>

    </div>
  </div>
</div>

{% endblock %}