project/server/admin/views.py
# project/server/admin/views.py


###########
# imports #
###########

from functools import wraps
from flask import render_template, Blueprint, request, flash, redirect, \
    url_for, jsonify
from flask.ext.login import login_required
from flask.ext.login import current_user
from sqlalchemy import exc

from project.server import db
from project.server.models import Course, Teacher, Student
from project.server.admin.forms import UpdateCourseForm, AddCourseForm, \
    UpdateStudentForm, AddStudentForm, AddTeacherForm, UpdateTeacherForm


##########
# config #
##########

admin_blueprint = Blueprint('admin', __name__,)


###########
# helpers #
###########

def get_courses():
    return Course.query.all()


def get_teachers():
    return Teacher.query.all()


def get_students():
    return Student.query.all()


def get_teacher_id(teacher_email):
    teacher_object = Teacher.query.filter_by(email=teacher_email).first()
    return teacher_object.id


def get_single_course(course_id):
    return Course.query.filter_by(id=course_id).first()


def get_single_student(student_id):
    return Student.query.filter_by(id=student_id).first()


def get_single_student_by_email(student_email):
    return Student.query.filter_by(email=student_email).first()


def get_single_teacher(teacher_id):
    return Teacher.query.filter_by(id=teacher_id).first()


def get_available_students(course_id):
    """
    This function returns a list of students
    not currently taking a specific course
    """
    course = Course.query.filter_by(id=course_id).first()
    return list(set(get_students()) - set(course.students))


def validate_admin(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if current_user.is_admin() is False:
            flash(
                'You do not have the correct permissions to view that page.',
                'warning'
            )
            return redirect(url_for('user.login', next=request.url))
        return f(*args, **kwargs)
    return decorated_function


##########
# routes #
##########

@admin_blueprint.route('/admin/dashboard/')
@login_required
@validate_admin
def dashboard():
    return render_template(
        '/admin/dashboard.html',
        courses=get_courses(),
        students=get_students(),
        teachers=get_teachers()
    )


@admin_blueprint.route(
    '/admin/add_course',
    methods=['GET', 'POST']
)
@login_required
@validate_admin
def add_course():
    form = AddCourseForm(request.form)
    form.teachers.choices = [
        (teacher.email, teacher.email)
        for teacher in get_teachers()
    ]
    form.students.choices = [
        (students.email, students.email)
        for students in get_students()
    ]
    if form.validate_on_submit():
        new_course = Course(
            name=form.name.data,
            description=form.description.data,
            subject=form.subject.data,
            start_date=form.start_date.data,
            end_date=form.end_date.data,
            teacher_id=get_teacher_id(form.teachers.data)
        )
        if form.students.data:
            for student_email in form.students.data:
                new_student = get_single_student_by_email(student_email)
                new_course.students.append(new_student)
        try:
            db.session.add(new_course)
            db.session.commit()
            flash('Thank you for adding a new course.', 'success')
            return redirect('/admin/dashboard')
        except exc.SQLAlchemyError:
            flash('Something went wrong.', 'danger')
            return redirect('/admin/dashboard')
    return render_template('/admin/add_course.html', form=form)


@admin_blueprint.route(
    '/admin/update_course/<int:course_id>',
    methods=['GET', 'POST']
)
@login_required
@validate_admin
def update_course(course_id):
    current_students = False
    potential_students = False
    form = UpdateCourseForm(request.form)
    form.teachers.choices = [
        (teacher.email, teacher.email)
        for teacher in get_teachers()
    ]
    course = get_single_course(course_id)
    if course.students:
        form.current_students.choices = [
            (students.email, students.email)
            for students in course.students
        ]
        current_students = True
    available_students = get_available_students(course_id)
    if available_students:
        form.potential_students.choices = [
            (students.email, students.email)
            for students in available_students
        ]
        potential_students = True
    if form.validate_on_submit():
        update_course = course
        update_course.name = form.name.data
        update_course.description = form.description.data
        update_course.subject = form.subject.data
        update_course.start_date = form.start_date.data
        update_course.end_date = form.end_date.data
        update_course.teacher_id = get_teacher_id(form.teachers.data)
        if form.potential_students.data:
            for student_email in form.potential_students.data:
                new_student = get_single_student_by_email(student_email)
                update_course.students.append(new_student)
        if form.current_students.data:
            for student_email in form.current_students.data:
                student = get_single_student_by_email(student_email)
                update_course.students.remove(student)
        try:
            db.session.commit()
            flash('Course updated. Thank you', 'success')
            return redirect('/admin/dashboard'.format(course_id))
        except exc.SQLAlchemyError:
            flash('Something went wrong.', 'danger')
            return redirect('/admin/dashboard'.format(course_id))
    return render_template(
        '/admin/update_course.html',
        form=form,
        single_course=course,
        current_students=current_students,
        potential_students=potential_students
    )


@admin_blueprint.route(
    '/admin/course/<int:course_id>',
    methods=['DELETE']
)
@login_required
@validate_admin
def delete_course(course_id):
    course = get_single_course(course_id)
    try:
        db.session.delete(course)
        db.session.commit()
        return jsonify({'status': '{0} removed!'.format(course.name)})
    except exc.SQLAlchemyError:
        return jsonify({'status': 'Something went wrong.'})


@admin_blueprint.route(
    '/admin/add_student',
    methods=['GET', 'POST']
)
@login_required
@validate_admin
def add_student():
    form = AddStudentForm(request.form)
    if form.validate_on_submit():
        new_student = Student(
            email=form.email.data,
            password=form.password.data
        )
        try:
            db.session.add(new_student)
            db.session.commit()
            flash('Thank you for adding a new student.', 'success')
            return redirect('/admin/dashboard')
        except exc.SQLAlchemyError:
            flash('Something went wrong.', 'danger')
            return redirect('/admin/dashboard')
    return render_template('/admin/add_student.html', form=form)


@admin_blueprint.route(
    '/admin/update_student/<int:student_id>',
    methods=['GET', 'POST']
)
@login_required
@validate_admin
def update_student(student_id):
    form = UpdateStudentForm(request.form)
    student = get_single_student(student_id)
    if form.validate_on_submit():
        update_student = student
        update_student.email = form.email.data
        update_student.registered_on = form.registered_on.data
        try:
            db.session.commit()
            flash('Student updated. Thank you', 'success')
            return redirect('/admin/dashboard')
        except exc.SQLAlchemyError:
            flash('Something went wrong.', 'danger')
            return redirect('/admin/dashboard')
    return render_template(
        '/admin/update_student.html',
        form=form,
        single_student=student
    )


@admin_blueprint.route(
    '/admin/student/<int:student_id>',
    methods=['DELETE']
)
@login_required
@validate_admin
def delete_student(student_id):
    student = get_single_student(student_id)
    try:
        db.session.delete(student)
        db.session.commit()
        return jsonify({'status': '{0} removed!'.format(student.email)})
    except exc.SQLAlchemyError:
        return jsonify({'status': 'Something went wrong.'})


@admin_blueprint.route(
    '/admin/add_teacher',
    methods=['GET', 'POST']
)
@login_required
@validate_admin
def add_teacher():
    form = AddTeacherForm(request.form)
    if form.validate_on_submit():
        new_teacher = Teacher(
            email=form.email.data,
            password=form.password.data
        )
        try:
            db.session.add(new_teacher)
            db.session.commit()
            flash('Thank you for adding a new teacher.', 'success')
            return redirect('/admin/dashboard')
        except exc.SQLAlchemyError:
            flash('Something went wrong.', 'danger')
            return redirect('/admin/dashboard')
    return render_template('/admin/add_teacher.html', form=form)


@admin_blueprint.route(
    '/admin/update_teacher/<int:teacher_id>',
    methods=['GET', 'POST']
)
@login_required
@validate_admin
def update_teacher(teacher_id):
    form = UpdateTeacherForm(request.form)
    teacher = get_single_teacher(teacher_id)
    if form.validate_on_submit():
        update_teacher = teacher
        update_teacher.email = form.email.data
        update_teacher.registered_on = form.registered_on.data
        try:
            db.session.commit()
            flash('Teacher updated. Thank you', 'success')
            return redirect('/admin/dashboard')
        except exc.SQLAlchemyError:
            flash('Something went wrong.', 'danger')
            return redirect('/admin/dashboard')
    return render_template(
        '/admin/update_teacher.html',
        form=form,
        single_teacher=teacher
    )


@admin_blueprint.route(
    '/admin/teacher/<int:teacher_id>',

project/server/main/views.py
# project/server/main/views.py


###########
# imports #
###########

from flask import render_template, Blueprint


##########
# config #
##########

main_blueprint = Blueprint('main', __name__,)


##########
# routes #
##########


@main_blueprint.route('/')
def home():
    return render_template('main/home.html')


@main_blueprint.route("/about")
def about():
    return render_template('main/about.html')

project/server/student/views.py
# project/server/student/views.py


###########
# imports #
###########

from functools import wraps
from flask import render_template, Blueprint, request, flash, redirect, url_for
from flask.ext.login import login_required
from flask.ext.login import current_user
from sqlalchemy import exc

from project.server import db
from project.server.student.forms import AddCourseForm
from project.server.models import Course, Student


##########
# config #
##########

student_blueprint = Blueprint('student', __name__,)


###########
# helpers #
###########

def get_all_courses():
    return Course.query.all()


def get_single_course(course_id):
    return Course.query.filter_by(id=course_id).first()


def get_single_course_name(course_name):
    return Course.query.filter_by(name=course_name).first()


def get_student(user_id):
    return Student.query.filter_by(id=user_id).first()


def get_available_courses(user_id):
    student_courses = get_student(user_id).courses
    return list(set(get_all_courses()) - set(student_courses))


def validate_student(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if current_user.is_student() is False:
            flash(
                'You do not have the correct permissions to view that page.',
                'warning'
            )
            return redirect(url_for('user.login', next=request.url))
        return f(*args, **kwargs)
    return decorated_function


##########
# routes #
##########


@student_blueprint.route('/student/courses')
@login_required
@validate_student
def show_courses():
    return render_template('/student/courses.html')


@student_blueprint.route('/student/course/<int:course_id>')
@login_required
@validate_student
def show_single_course(course_id):
    return render_template(
        '/student/description.html',
        single_course=get_single_course(course_id)
    )


@student_blueprint.route(
    '/student/add_course',
    methods=['GET', 'POST']
)
@login_required
@validate_student
def add_course():
    available_courses = get_available_courses(current_user.get_id())
    if available_courses:
        form = AddCourseForm(request.form)
        form.courses.choices = [
            (single_course.name, single_course.name)
            for single_course in available_courses
        ]
        if form.validate_on_submit():
            course = get_single_course_name(form.courses.data)
            user = Student.query.filter_by(id=current_user.get_id()).first()
            course.students.append(user)
            try:
                db.session.commit()
                flash('Thank you for adding a new course.', 'success')
                return redirect('/student/courses')
            except exc.SQLAlchemyError:
                flash('Something went wrong.', 'danger')
                return redirect('/student/courses')
        return render_template('/student/add.html', form=form)
    else:
        flash('No new courses at this time.', 'warning')
        return render_template('/student/add.html')

project/server/user/views.py
# project/server/user/views.py


###########
# imports #
###########

from flask import render_template, Blueprint, url_for, \
    redirect, flash, request
from flask.ext.login import login_user, logout_user, login_required, \
    current_user
from sqlalchemy import exc

from project.server import bcrypt, db
from project.server.models import User, Student
from project.server.user.forms import LoginForm, RegisterForm, PasswordForm

##########
# config #
##########

user_blueprint = Blueprint('user', __name__,)


##########
# routes #
##########

@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = Student(
            email=form.email.data,
            password=form.password.data
        )
        try:
            db.session.add(user)
            db.session.commit()
            login_user(user)
            flash('Thank you for registering.', 'success')
            return redirect(url_for("main.home"))
        except exc.SQLAlchemyError:
            flash('Something went wrong.', 'danger')
            return redirect(url_for("main.home"))

    return render_template('user/register.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']
        ):
            login_user(user)
            flash('You are logged in. Welcome!', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', title='Please Login', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out. Bye!', 'success')
    return redirect(url_for('main.home'))


@user_blueprint.route('/password', methods=['GET', 'POST'])
@login_required
def password():
    form = PasswordForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(id=current_user.get_id()).first()
        user.password = bcrypt.generate_password_hash(form.password.data)
        try:
            db.session.commit()
            flash('Password Updated!', 'success')
            return redirect(url_for('main.home'))
        except exc.SQLAlchemyError:
            flash('Something went wrong.', 'danger')
            return redirect(url_for('main.home'))
    return render_template('user/password.html', form=form)

project/client/templates/_base.html
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <title>LMS{% block title %}{% endblock %}</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.5/yeti/bootstrap.min.css" rel="stylesheet">
    <link href="{{url_for('static', filename='main.css')}}" rel="stylesheet" media="screen">
    {% block css %}{% endblock %}
  </head>

  <body>

    {% include 'header.html' %}

    <div class="site-content">
      <div class="container">

        <!-- messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
          <br>
          <div class="row">
            <div class="col-md-12">
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
                 {{message}}
                </div>
              {% endfor %}
            </div>
          </div>
          {% endif %}
        {% endwith %}

        <!-- ajax messages -->
        <br>
        <div class="row">
          <div class="col-md-12">
            <div id="ajax-alert">
            </div>
          </div>
        </div>

        <!-- child template -->
        {% block content %}{% endblock %}

        <br>

        <!-- errors -->
        {% if error %}
          <p class="error"><strong>Error:</strong> {{ error }}</p>
        {% endif %}

      </div>
    </div>

    <br><br>

    {% include 'footer.html' %}

    <!-- scripts -->
    <script src="//code.jquery.com/jquery-1.11.2.min.js" type="text/javascript"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="{{url_for('static', filename='main.js')}}" type="text/javascript"></script>
    {% block js %}{% endblock %}

  </body>
</html>

project/client/templates/footer.html
<footer class="footer">
  <div class="container">
    <hr>
    <small>
      <span>© <a href="mailto:michael@realpython.com">Michael Herman</a></span>
    </small>
  </div>
</footer>

project/client/templates/header.html
<header class="site-header">
  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <a class="navbar-brand" href="{{ url_for('main.home') }}">LMS</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="{{ url_for('main.about') }}">About</a></li>
          {% if current_user.is_authenticated and not current_user.is_admin() %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Courses <span class="caret"></span></a>
              <ul class="dropdown-menu">
                {% if current_user.is_student() %}
                  <li><a href="{{ url_for('student.show_courses') }}">View Courses</a></li>
                  <li><a href="{{ url_for('student.add_course') }}">Add New Course</a></li>
                {% elif current_user.is_teacher() %}
                  <li><a href="{{ url_for('teacher.show_courses') }}">View Courses</a></li>
                  <li><a href="{{ url_for('teacher.add_course') }}">Add New Course</a></li>
                {% endif %}
              </ul>
            </li>
          {% elif current_user.is_authenticated and current_user.is_admin() %}
            <li><a href="{{ url_for('admin.dashboard') }}">Dashboard</a></li>
          {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('user.password') }}">Update Password</a></li>
            <li><a href="{{ url_for('user.logout') }}">Logout</a></li>
          {% else %}
            <li><a href="{{ url_for('user.login') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;Register/Login</a></li>
          {% endif %}
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
  </nav>
</header>

project/client/templates/register.html
<!doctype html>
<html>
	<head>
		<link href="/static/bootstrap.min.css" rel="stylesheet" />
		<title>Create an Account</title>
		<style>
			h1 {
				margin: 50px 0;
			}
			fieldset span {
				//margin-right: 20px;
			}
			
			fieldset div {
				margin-top: 25px;
			}
		</style>
	</head>
	<body>
		<div class="container">
			<div class="row-fluid">
				<h1 style="text-align: center;">Create an Account</h1>
			</div>
			<div class="row-fluid text-center">
				<form class="form-horizontal well" method="post" action="/register/">
				<fieldset>
					<div style="margin-top: 0;"><span>Username:  </span><input type="text" name="username" class="input-xlarge" required/></div>
					<div><span>Password:  </span><input type="password" class="input-xlarge" name="password"  required/></div>
					<div><span>Is a Teacher? </span><input type="checkbox" name="isTeacher" value="1"  required/></div>
					<div><span>Name: </span><input type="text" class="input-xlarge" name="name"  required/></div>
					<div><span>Email: </span><input type="email" class="input-xlarge"name="email"  required/></div>
					<div><input type="submit" class="btn btn-primary btn-large" value="Submit"></div>
					{% with messages = get_flashed_messages() %}
						{% if messages %}
							{% for message in messages %}
								<div class="alert alert-success" style="margin: 0 auto;">
									<strong>{{ message }}</strong>
								</div>
							{% endfor %}
						{% endif %}
					{% endwith %}
				</fieldset>
				</form>
				<!--<form method="POST" action="/register/">
					<input type="text" name="username" />
					<input type="submit" value="submit"/>
				</form>-->
			</div>
		</div>
	</body>
</html>